import type { TileId, TileKind, SeatIndex, Meld } from "@mahjong/shared";
import { ActionType, MeldType, RoundPhase, GamePhase } from "@mahjong/shared";
import type { GameState, RoundState } from "./game-state";
import { tileKind, isTerminalOrHonor, isSimple, countByKind, sortTileIds, tileSuit, tileNumber } from "./tile";
import { isWinningHand, isTenpai, findWaitingTiles, calculateShanten } from "./hand";
import type { GameMachine, GameAction } from "./game-machine";

/**
 * Simple bot AI for demo play.
 * Strategy: discard isolated tiles first, prefer tanyao-like hands.
 */
export function botDecideAction(
  state: GameState,
  seat: SeatIndex,
  availableActions: ActionType[]
): GameAction | null {
  if (availableActions.length === 0) return null;

  const round = state.round;
  if (!round) return null;

  // Priority: Tsumo > Ron > Riichi > Pon > Chi > Discard > Skip
  if (availableActions.includes(ActionType.TSUMO)) {
    return { seat, action: ActionType.TSUMO };
  }

  if (availableActions.includes(ActionType.RON)) {
    return { seat, action: ActionType.RON };
  }

  if (availableActions.includes(ActionType.RIICHI)) {
    // Declare riichi if tenpai
    const tileToDiscard = chooseBestDiscard(round, seat);
    if (tileToDiscard !== null) {
      // Check if discarding this tile keeps us tenpai
      const hand = round.hands[seat];
      const remaining = hand.filter((t) => t !== tileToDiscard).map(tileKind);
      if (isTenpai(remaining)) {
        return { seat, action: ActionType.RIICHI, tileId: tileToDiscard };
      }
    }
  }

  // Pon if it improves the hand significantly
  if (availableActions.includes(ActionType.PON) && round.lastDiscard) {
    const discardKind = tileKind(round.lastDiscard.tileId);
    const hand = round.hands[seat];
    const handKinds = hand.map(tileKind);
    const matchCount = handKinds.filter((k) => k === discardKind).length;

    // Pon yakuhai or if we have 2+ matching and hand is good
    if (matchCount >= 2) {
      const isYakuhai = discardKind >= 31 || discardKind === 27 + state.roundWind;
      if (isYakuhai || Math.random() < 0.3) {
        const ponTiles = hand.filter((t) => tileKind(t) === discardKind).slice(0, 2);
        return {
          seat,
          action: ActionType.PON,
          tiles: [...ponTiles, round.lastDiscard.tileId],
        };
      }
    }
  }

  // Discard
  if (availableActions.includes(ActionType.DISCARD)) {
    const tileToDiscard = chooseBestDiscard(round, seat);
    if (tileToDiscard !== null) {
      return { seat, action: ActionType.DISCARD, tileId: tileToDiscard };
    }
  }

  // Skip any claims we don't want
  if (availableActions.includes(ActionType.SKIP)) {
    return { seat, action: ActionType.SKIP };
  }

  return null;
}

/**
 * Choose the best tile to discard.
 * Strategy: discard isolated honor/terminal tiles first, then most isolated tiles.
 */
function chooseBestDiscard(round: RoundState, seat: SeatIndex): TileId | null {
  const hand = round.hands[seat];
  if (hand.length === 0) return null;

  // If in riichi, must discard the drawn tile (tsumogiri)
  if (round.riichi[seat] && round.drawnTile !== null) {
    return round.drawnTile;
  }

  const handKinds = hand.map(tileKind);
  const counts = countByKind(hand);

  // Score each tile for discard priority (higher = discard first)
  const scores: { tileId: TileId; score: number }[] = hand.map((tileId) => {
    const kind = tileKind(tileId);
    let score = 0;

    // Single isolated tiles score high (discard them)
    if (counts[kind] === 1) score += 10;

    // Terminal/honor tiles with no connection
    if (isTerminalOrHonor(kind)) {
      score += 5;
      // Unless it's a pair or triplet
      if (counts[kind] >= 2) score -= 15;
    }

    // Tiles with no adjacent tiles (isolated number tiles)
    if (kind < 27) {
      const suit = Math.floor(kind / 9);
      const num = kind % 9;
      const hasAdj1 = num > 0 && counts[suit * 9 + num - 1] > 0;
      const hasAdj2 = num < 8 && counts[suit * 9 + num + 1] > 0;
      if (!hasAdj1 && !hasAdj2) score += 8;
      else if (hasAdj1 && hasAdj2) score -= 5; // part of sequence
    }

    // Pairs score lower (keep them)
    if (counts[kind] === 2) score -= 3;
    // Triplets score very low (keep them)
    if (counts[kind] >= 3) score -= 10;

    // Prefer discarding drawn tile as a tie-breaker (ツモ切り)
    if (tileId === round.drawnTile) score += 0.5;

    return { tileId, score };
  });

  // Sort by score descending
  scores.sort((a, b) => b.score - a.score);
  return scores[0].tileId;
}

/**
 * Run bot actions for all non-human players.
 * Returns events generated by bot actions.
 */
export function runBotActions(
  machine: GameMachine,
  humanSeat: SeatIndex
): void {
  const state = machine.getState();
  if (state.gamePhase !== GamePhase.PLAYING || !state.round) return;

  // Process claims for all bot players
  for (let i = 0; i < 4; i++) {
    const seat = i as SeatIndex;
    if (seat === humanSeat) continue;

    const available = machine.getAvailableActions(seat);
    if (available.length === 0) continue;

    const action = botDecideAction(state, seat, available);
    if (action) {
      machine.processAction(action);
      // State might have changed, re-check
      runBotActions(machine, humanSeat);
      return;
    }
  }
}
